version: "2"

services:
  pg:
    image: postgres
    ports:
      - "5432:5432"

  acraserver:
    image: acraserver
    depends_on:
      - pg
    links:
      - pg:postgresql_link

  acraproxy:
    image: acraproxy
    depends_on:
      - acraserver
    ports:
      - "9494:9494"
    links:
      - acraserver:acraserver_link
