# Connection string to Acra's API like tcp://x.x.x.x:yyyy or unix:///path/to/socket
acra_api_connection_string: 

# Port of Acra HTTP api
acra_commands_port: 9090

# Connection string to AcraServer like tcp://x.x.x.x:yyyy or unix:///path/to/socket
acra_connection_string: 

# IP or domain to acra daemon
acra_host: 

# Expected id from AcraServer for Secure Session
acra_id: acra_server

# Port of acra daemon
acra_port: 9393

# Client id
client_id: 

# Port for AcraConnector HTTP api
command_port: 9191

# path to config
config: 

# Connection string like tcp://x.x.x.x:yyyy or unix:///path/to/socket
connection_api_string: tcp://127.0.0.1:9191/

# Connection string like tcp://x.x.x.x:yyyy or unix:///path/to/socket
connection_string: tcp://127.0.0.1:9494/

# Disable checking that connections from app running from another user
disable_user_check: false

# dump config
dumpconfig: false

# Enable HTTP API
enable_http_api: false

# Folder from which will be loaded keys
keys_dir: .acrakeys

# Logging format: plaintext, json or CEF
logging_format: plaintext

# Use raw transport (tcp/unix socket) between acraserver and acraproxy/client (don't use this flag if you not connect to database with ssl/tls
no_encryption: false

# Port to AcraConnector
port: 9494

# Use tls to encrypt transport between AcraServer and AcraConnector/client
tls: false

# Set authentication mode that will be used in TLS connection with Postgresql. Values in range 0-4 that set auth type (https://golang.org/pkg/crypto/tls/#ClientAuthType). Default is tls.RequireAndVerifyClientCert
tls_auth: 4

# Path to root certificate which will be used with system root certificates to validate AcraServer's certificate
tls_ca: 

# Path to certificate
tls_cert: 

# Path to private key that will be used in TLS handshake with AcraServer
tls_key: 

# Expected Server Name (SNI) from AcraServer
tls_sni: 

# Log to stderr
v: false

